server:
  port: 8800

spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com:
      jiahao:
        debug
